In [16]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [17]:
dat=pd.read_csv('/home/maria/neural-computation-blog-python-code/Allen-Stimulus-Response/first_q_test.csv')

In [18]:
clip_columns = dat.filter(regex='var_exp_clip_\d+')
dino_columns = dat.filter(regex='var_exp_dino_\d+')
vit_columns= dat.filter(regex='var_exp_vit_\d+')

In [19]:
print(vit_columns)

     var_exp_vit_0  var_exp_vit_1  var_exp_vit_2  var_exp_vit_3  \
0         0.447519      -0.074915      -0.189859      -0.070365   
1        -0.119796      -0.495418      -0.188268      -0.160370   
2        -0.145695      -0.228753       0.672255       0.049792   
3         0.040555      -0.168109      -0.186316      -0.152236   
4         0.674260       0.008406      -0.080595       0.695127   
..             ...            ...            ...            ...   
207       0.428332      -0.147728      -0.148001       0.617587   
208      -0.117557      -0.193745      -0.204770      -0.170890   
209      -0.115634      -0.255113      -0.219874      -0.114891   
210       0.787975      -0.020269      -0.226161       0.038499   
211      -0.054968      -0.214786      -0.092067      -0.150118   

     var_exp_vit_4  var_exp_vit_5  var_exp_vit_6  var_exp_vit_7  \
0        -0.109160       0.491661       0.390736      -0.148701   
1        -0.156324      -0.341345      -0.026993      -0.3782

In [20]:

for i in range(0,10):
    print(np.corrcoef(clip_columns.iloc[:,i].T,vit_columns.iloc[:,i].T))

[[1.         0.98223548]
 [0.98223548 1.        ]]
[[1.         0.97981924]
 [0.97981924 1.        ]]
[[1.         0.98472526]
 [0.98472526 1.        ]]
[[1.         0.98625882]
 [0.98625882 1.        ]]
[[1.         0.97755736]
 [0.97755736 1.        ]]
[[1.         0.97711769]
 [0.97711769 1.        ]]
[[1.         0.97829186]
 [0.97829186 1.        ]]
[[1.         0.97162231]
 [0.97162231 1.        ]]
[[1.         0.98475191]
 [0.98475191 1.        ]]
[[1.         0.98119457]
 [0.98119457 1.        ]]


In [23]:
for i in range(0,10):
    print(np.corrcoef(clip_columns.iloc[:,i].T,dino_columns.iloc[:,i].T))

[[1.         0.98683025]
 [0.98683025 1.        ]]
[[1.         0.98118749]
 [0.98118749 1.        ]]
[[1.         0.98530909]
 [0.98530909 1.        ]]
[[1.         0.98778706]
 [0.98778706 1.        ]]
[[1.         0.97755965]
 [0.97755965 1.        ]]
[[1.         0.98092919]
 [0.98092919 1.        ]]
[[1.         0.97904333]
 [0.97904333 1.        ]]
[[1.        0.9697279]
 [0.9697279 1.       ]]
[[1.        0.9848543]
 [0.9848543 1.       ]]
[[1.       0.982531]
 [0.982531 1.      ]]


In [24]:
for i in range(0,10):
    print(np.corrcoef(dino_columns.iloc[:,i].T,vit_columns.iloc[:,i].T))

[[1.         0.98581787]
 [0.98581787 1.        ]]
[[1.         0.98586035]
 [0.98586035 1.        ]]
[[1.         0.98490597]
 [0.98490597 1.        ]]
[[1.       0.988232]
 [0.988232 1.      ]]
[[1.         0.98573583]
 [0.98573583 1.        ]]
[[1.        0.9866577]
 [0.9866577 1.       ]]
[[1.         0.98434988]
 [0.98434988 1.        ]]
[[1.         0.98203578]
 [0.98203578 1.        ]]
[[1.         0.98843554]
 [0.98843554 1.        ]]
[[1.        0.9861175]
 [0.9861175 1.       ]]
