In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
dat=pd.read_csv('/home/maria/neural-computation-blog-python-code/Allen-Stimulus-Response/first_q_test.csv')

In [3]:
clip_columns = dat.filter(regex='var_exp_clip_\d+')
dino_columns = dat.filter(regex='var_exp_dino_\d+')
vit_columns= dat.filter(regex='var_exp_vit_\d+')

In [11]:
print(vit_columns)

     var_exp_vit_0  var_exp_vit_1  var_exp_vit_2  var_exp_vit_3  \
0         0.088367      -0.021250      -0.023926      -0.005261   
1        -0.070950      -0.095125      -0.080525      -0.029496   
2        -0.086635      -0.108883       0.204169      -0.004970   
3        -0.026986      -0.020718      -0.017516      -0.058239   
4         0.228179       0.031509      -0.042608       0.419844   
..             ...            ...            ...            ...   
207       0.142753       0.001231      -0.031145       0.217106   
208      -0.039035      -0.050208      -0.006565      -0.033742   
209      -0.028818      -0.028852      -0.047261      -0.004894   
210       0.200595      -0.024740      -0.033272      -0.014761   
211      -0.021580      -0.035466      -0.006561      -0.056820   

     var_exp_vit_4  var_exp_vit_5  var_exp_vit_6  var_exp_vit_7  \
0        -0.057160       0.142109       0.108629      -0.065696   
1        -0.045603      -0.040204      -0.018493      -0.0618

In [13]:

for i in range(0,10):
    print(np.corrcoef(clip_columns.iloc[:,i].T,vit_columns.iloc[:,i].T))

[[1.         0.83245248]
 [0.83245248 1.        ]]
[[1.         0.90044815]
 [0.90044815 1.        ]]
[[1.         0.86692405]
 [0.86692405 1.        ]]
[[1.         0.84379242]
 [0.84379242 1.        ]]
[[1.         0.87912304]
 [0.87912304 1.        ]]
[[1.         0.87770923]
 [0.87770923 1.        ]]
[[1.         0.87613808]
 [0.87613808 1.        ]]
[[1.         0.84705012]
 [0.84705012 1.        ]]
[[1.         0.86093122]
 [0.86093122 1.        ]]
[[1.         0.86332066]
 [0.86332066 1.        ]]


In [14]:
for i in range(0,10):
    print(np.corrcoef(clip_columns.iloc[:,i].T,dino_columns.iloc[:,i].T))

[[1.         0.98683025]
 [0.98683025 1.        ]]
[[1.         0.98118749]
 [0.98118749 1.        ]]
[[1.         0.98530909]
 [0.98530909 1.        ]]
[[1.         0.98778706]
 [0.98778706 1.        ]]
[[1.         0.97755965]
 [0.97755965 1.        ]]
[[1.         0.98092919]
 [0.98092919 1.        ]]
[[1.         0.97904333]
 [0.97904333 1.        ]]
[[1.        0.9697279]
 [0.9697279 1.       ]]
[[1.        0.9848543]
 [0.9848543 1.       ]]
[[1.       0.982531]
 [0.982531 1.      ]]


In [15]:
for i in range(0,10):
    print(np.corrcoef(dino_columns.iloc[:,i].T,vit_columns.iloc[:,i].T))

[[1.         0.82450413]
 [0.82450413 1.        ]]
[[1.         0.90450363]
 [0.90450363 1.        ]]
[[1.         0.86764757]
 [0.86764757 1.        ]]
[[1.         0.83464691]
 [0.83464691 1.        ]]
[[1.         0.87975801]
 [0.87975801 1.        ]]
[[1.         0.88180358]
 [0.88180358 1.        ]]
[[1.         0.87043509]
 [0.87043509 1.        ]]
[[1.         0.85796405]
 [0.85796405 1.        ]]
[[1.         0.86247821]
 [0.86247821 1.        ]]
[[1.         0.86481877]
 [0.86481877 1.        ]]
